Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 1024
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "10.0.0.10"
    web.vm.provision "shell", path: "upgrade_ubuntu.sh"
    web.vm.provision "shell", path: "install_java8_ubuntu.sh"
  end

  config.vm.define "database" do |db|
    db.vm.network "private_network", ip: "10.0.0.11"
    db.vm.provision "shell", path: "upgrade_ubuntu.sh"
    db.vm.provision "shell", path: "install_postgresql_ubuntu.sh"
  end

end
