Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define :centosserver do |centosserver_config|
      centosserver_config.vm.network "private_network", ip: "192.168.50.254", netmask: "24"
  end
end