Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.define :ubuntuserver do |ubuntuserver_config|
      
    ubuntuserver_config.vm.network "private_network", ip: "192.168.50.100", netmask: "24"
      
    ubuntuserver_config.vm.provision "shell", path: "manifests/install_puppet.sh"
      
    ubuntuserver_config.vm.provision "puppet" do |puppet|
      puppet.manifest_file = "ubuntuServer.pp"
    end
    
  end

end